/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f76107e3-d374-4f45-883b-5bfea4ca5dd9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Ag1DJ56zy",
    "aws_user_pools_web_client_id": "6q431rsrfrbteccluagbdl5ucs",
    "oauth": {
        "domain": "sondratulalaphotograaaef21f8-aaef21f8-main.auth.us-east-1.amazoncognito.com",
        "scope": [
            "email",
            "openid",
            "profile"
        ],
        "redirectSignIn": "https://sondratulalaphotography.com/,http://localhost:5173/,http://localhost:3000/,http://localhost:5173/,http://localhost:3000/,https://sondratulalaphotography.com/,http://localhost:3001/",
        "redirectSignOut": "https://sondratulalaphotography.com/,http://localhost:5173/,http://localhost:3000/,http://localhost:3001/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "sondratulalaphotogra25f72088efde4213955fdfd598b496bb-main",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
