/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "api4593058b",
            "endpoint": "https://wih6fo5l5k.execute-api.us-east-1.amazonaws.com/gentest",
            "region": "us-east-1"
        },
        {
            "name": "apid5657c10",
            "endpoint": "https://x3d82dv9qb.execute-api.us-east-1.amazonaws.com/gentest",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:9aa03d30-490e-4a9b-ae75-0eec62bd2386",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_fhyEhGyB1",
    "aws_user_pools_web_client_id": "570fsn8ba7t0prioh62et7ejb2",
    "oauth": {
        "domain": "sondratulalaphotograaaef21f8-aaef21f8-gentest.auth.us-east-1.amazoncognito.com",
        "scope": [
            "email",
            "openid",
            "profile"
        ],
        "redirectSignIn": "https://sondratulalaphotography.com/,http://localhost:5173/,http://localhost:3000/,http://localhost:3001/",
        "redirectSignOut": "https://sondratulalaphotography.com/,http://localhost:5173/,http://localhost:3000/,http://localhost:3001/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "sondratulalaphotogra25f72088efde4213955fdfd598b9bd46-gentest",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
